version: '3.8'

services:
  # API Gateway (Node.js)
  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./gateway:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - auth
      - social
      - message

  # Auth Service (Go)
  auth:
    build:
      context: .
      dockerfile: services/auth/Dockerfile
    ports:
      - "50051:50051"
    volumes:
      - ./services/auth:/app
    environment:
      - GO_ENV=development
    depends_on:
      - db

  # Social Service (Go)
  social:
    build:
      context: .
      dockerfile: services/social/Dockerfile
    ports:
      - "8081:8081"
    volumes:
      - ./services/social:/app
    environment:
      - GO_ENV=development
    depends_on:
      - db

  # Message Service (Go)
  message:
    build:
      context: .
      dockerfile: services/message/Dockerfile
    ports:
      - "8083:8083"
      - "50052:50052"
    volumes:
      - ./services/message:/app
    environment:
      - GO_ENV=development
    depends_on:
      - db

  # Database (Example: PostgreSQL)
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    volumes:
      - postgres_data:/var/lib/postgresql/data

# Volumes for persistent data
volumes:
  postgres_data: