# Use an official Node.js runtime as a parent image
FROM oven/bun:canary-alpine

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the package.json and package-lock.json files
COPY gateway/package*.json ./

# Install dependencies
RUN bun install

# Copy the rest of the gateway code
COPY gateway/ .

# Expose the port the app runs on (adjust as needed)
EXPOSE 3000

# Command to run the application
CMD ["bun", "run", "start"]